import { COLORS, BACKGROUND_COLORS, SHADOW_COLORS } from './colors';
import { BREAKPOINT_LARGE, BREAKPOINT_MEDIUM, BREAKPOINT_SMALL } from './breakpoints';
import { EMAIL_VALIDATION, PASSWORD_VALIDATION,
    USERNAME_VALIDATION } from './form';
import { CONFIRM_PASSWORD, PASSWORD } from './data';

export {
    COLORS,
    BACKGROUND_COLORS,
    SHADOW_COLORS,
    BREAKPOINT_LARGE,
    BREAKPOINT_MEDIUM,
    BREAKPOINT_SMALL,
    EMAIL_VALIDATION,
    PASSWORD_VALIDATION,
    USERNAME_VALIDATION,
    CONFIRM_PASSWORD,
    PASSWORD,
}